services:
  - type: web
    name: ticket-booking-backend
    env: go
    region: ohio
    plan: free
    buildCommand: go build -o main ./cmd/api
    startCommand: ./main
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ticket-booking-db
          property: connectionString

  - type: psql
    name: ticket-booking-db
    region: ohio
    plan: free
    postgresMajorVersion: 15
